version: "3.9"

services:


  api:
    build: .
    container_name: orgs_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db


  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

volumes:
  pgdata: